/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bdfa43c8-7551-4a5a-86e9-3d1a88e1a691",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1cMSkb9jN",
    "aws_user_pools_web_client_id": "5sulb5jllk2nb3mufqj5voq0v",
    "oauth": {}
};


export default awsmobile;
